apiVersion: v1                                                                                                                               
kind: Service                                                                                
metadata:                                                                                    
  name: blogweb-service                                                                             
spec:                                                                                        
  selector:                                                                                  
    run: blogweb                                                                               
  ports:                                                                                    
  - port: 8080                                                                               
    targetPort: 8080
