FROM ubuntu:latest                                                                                             
MAINTAINER chen.wu@yeepay.com                                                                                                                       
COPY . /usr/local/                                                                                                                   
WORKDIR /usr/local/
EXPOSE 8080  
CMD ["./blog"]  







