apiVersion: apps/v1beta1                                                                                                                     
kind: Deployment                                                                             
metadata:                                                                                    
  name: redis                                                                                
spec:                                                                                        
  replicas: 1                                                                                
  template:                                                                                  
    metadata:                                                                                
      labels:                                                                                
        run: redis                                                                           
    spec:                                                                                    
      containers:                                                                            
      - name: redis                                                                          
        image: redis                                                                         
        ports:                                                                               
        - containerPort: 6379                                                                
                                                                                             
---                                                                                          
apiVersion: v1                                                                                
kind: Service                                                                                
metadata:                                                                                    
  name: redis-svc                                                                             
spec:                                                                                        
  selector:                                                                                  
    run: redis                                                                               
  ports:                                                                                     
  - port: 6379                                                                               
    targetPort: 6379  
